### ISSUE TITLE
Offset?

### ISSUE THREAD

**Issue by joelsawyer** [johnpolacek/extra-strength-responsive-grids#1]
amazing stuff... but unless I missed it, I don't see anything for offsets.  That would be a great addition.

**Comment by johnpolacek** [comment]
Personally I always thought offsets were a waste, but I finally ran into a situation where I wanted them. ESRG co-creator Andrew Pulley was always in favor of them, so I bet he's happy now. (Pulley - I still think .row is a waste)

**Comment by joelsawyer** [comment]
Don't use offsets all the time, but there certainly are those times when it comes in handy. Thanks for the update. (and I concur with the .row sentiment)
